### ISSUE TITLE
Ionic 3

### ISSUE THREAD

**Issue by dayanfcosta** [vijtad/SpeechRecognizer#1]
Hi there,

I was not able to add this plugin to my Ionic 3 project, when I execute "ionic cordova plugin add https://github.com/vijtad/SpeechRecognizer" it runs and that throws an error like that: 

`
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: cmd: Command failed with exit code 1 Error output:
npm ERR! code 128
npm ERR! Command failed: C:\Program Files\Git\cmd\git.EXE submodule update -q --init --recursive
npm ERR! fatal: 'submodule' appears to be a git command, but we were not
npm ERR! able to execute it. Maybe git-submodule is broken?

`

**Comment by roymasad** [comment]
Same issue here

Can't install without it throwing the following error 


(node:1724) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Failed to fetch plugin https://github.com/vijtad/SpeechRecognizer via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: cmd: Command failed with exit code 4294963238 Error output:

**Comment by vijtad** [comment]
This should work in Ionic 2 and I think this not compatible with Ionic 3.
